// Generated by Wrangler by running `wrangler types --x-include-runtime`

interface Env {
	YOUTUBE_API_KEY: "AIzaSyA4wNCgyd_gPXRHwZne21Vz5XdSAVMXPvo";
	CONVERTER_API_KEY: "7cd25bff43msh3ecf4927ff69a77p1cae86jsn9fffe932dfdd";
	ORIGIN: string;
	AUDIO: R2Bucket;
	ALBUM_COVERS: R2Bucket;
	DB: D1Database;
}
